### ISSUE TITLE
support to validate one or more item in slice 

### ISSUE THREAD

**Issue by vivekbasappa** [kudobuilder/kuttl#209] opened 2020-09-14 18:40 UTC
**What would you like to be added**:
in the status if we need to validate and assert if some of the items exist in slice. there is no way to validate that. currently assert expects all the items in slice to be provided. example test step fails with "slice length mismatch: 1!= 8"

code kuttl/pkg/test/utils/subset.go 
linenumber : 50 
function where the change is needed:  IsSubset(expected, actual interface{}) error 

`
if reflect.TypeOf(expected).Kind() == reflect.Slice {
		if reflect.ValueOf(expected).Len() != reflect.ValueOf(actual).Len() {
			return &SubsetError{
				message: fmt.Sprintf("slice length mismatch: %d != %d", reflect.ValueOf(expected).Len(), reflect.ValueOf(actual).Len()),
			}
		}
		for i := 0; i < reflect.ValueOf(expected).Len(); i++ {
			if err := IsSubset(reflect.ValueOf(expected).Index(i).Interface(), reflect.ValueOf(actual).Index(i).Interface()); err != nil {
				return err
			}
		}
	}
`

**Why is this needed**:
we need a way to assert only given item in the slice . it should not expect all the items in the list. just like we assert fields in status now

**Comment by porridge** [comment] 2020-09-15 06:54
Looks like a duplicate of https://github.com/kudobuilder/kuttl/issues/76

**Closed by porridge** 2020-09-15 06:54 UTC
