### ISSUE TITLE
Kuttl runs all commands in TestSuite despite a timeout

### ISSUE THREAD

**Issue by porridge** [kudobuilder/kuttl#170] opened 2020-07-17 13:26 UTC
**What happened**:

```
$ cat <<END > kuttl-test.yaml
apiVersion: kudo.dev/v1alpha1
kind: TestSuite
commands:
        - command: sleep 3
        - command: echo step two
testDirs:
        - empty
timeout: 2
END
$ mkdir empty
$ kubectl kuttl test -v3
=== RUN   kuttl
    kuttl: harness.go:339: starting setup
    kuttl: harness.go:225: running tests using configured kubeconfig.
    kuttl: logger.go:42: 15:22:15 |  | running command: "sleep 3"
    kuttl: logger.go:42: 15:22:15 |  | running command: [sleep 3]
    kuttl: logger.go:42: 15:22:17 |  | running command: "echo step two"
    kuttl: logger.go:42: 15:22:17 |  | running command: [echo step two]
    kuttl: logger.go:42: 15:22:17 |  | step two
    kuttl: harness.go:458: fatal error running commands: [command "sleep 3" exceeded 2 sec timeout]
--- FAIL: kuttl (2.51s)
FAIL
```

**What you expected to happen**:

`echo step two` (or any other later command) to **not** be run

**How to reproduce it (as minimally and precisely as possible)**:

see above

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): N/A
- KUTTL version (use `kubectl kuttl version`): `KUTTL Version: version.Info{GitVersion:"0.4.0", GitCommit:"b85c5a0", BuildDate:"2020-06-02T15:49:56Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kensipe** [comment] 2020-07-17 13:50
interesting stuff @porridge !    This is an edge case which does NOT have a defined set of expectations... perhaps we need them.     A test in kuttl will end if there is an assertion failure... but I'm not sure without digging in if this is true for "test setup"... 
In the case this issue documents this is prior to any tests running.. this is setting up to setup tests :) 

summary:  Your defined expectations make sense.  We should implement them as you defined them here.

**Comment by kensipe** [comment] 2020-07-28 18:01
ok... part of the issue is that we are reusing `testutils.RunCommands` in 2 places which likely need different behavior.
1.  test setup (prior to any tests) - in this case, we likely do NOT want to run any tests if the cmd is not registered as ignore
2. teststep - in this case we are in the middle of a testsuite (and there could be additional testsuite enqueue).  This should mark a failure and continue.

I think in either case, if a command is not marked as ignore and a command fails, there should be no reason to continue to additional commands.   This area of the code predates my involvement... I looking to understand why a collection of errors was the solution here.  It was designed to do what it is currently doing :) 

Currently planning on modifying as detailed:
1. if command fails and is not marked as ignored, no more commands... return an error and calling code will do what's appropriate 
2. commands marked as ignored will be logged but ignored, continuing to next command
3. in kuttl test setup (beginning phase of test setup) fail with no tests run
4. in kuttl TestStep, fail this step

I think this will lead to removing the current array of errors from commands... I can't see their value... but we will see as I implement a solution.

**Comment by kensipe** [comment] 2020-07-28 18:28
Thanks @porridge for identifying this... super simple... it's a nice UX improvement

**Closed** 2020-07-29 19:45 UTC
